try {
    const x = 5;
    const d= x+y;
} catch (err) {
    console.log(err);
}


